#!/usr/bin/env bash
# render_comment.sh <findings.jsonl> <run-number> <commit-sha>
# Emits the PR comment markdown body to stdout. Marker on line 1 enables upsert.
set -uo pipefail
FILE="${1:?findings file required}"; RUN="${2:-?}"; SHA="${3:-?}"

# grep -c prints the count (0 when none) but exits 1 on no matches; capture the
# count and ignore the exit code (no `set -e`). Avoid `|| echo 0` which would
# append a second line and break the integer test.
hard="$(grep -c '"severity":"hard"' "$FILE" 2>/dev/null)"
[ -z "$hard" ] && hard=0
status="✅ All checks passed"
[ "$hard" -gt 0 ] && status="❌ Blocking issues found"

echo '<!-- skill-policy:report -->'
echo "## Skill Policy Check Report"
echo ""
echo "**Status:** $status · _Run #$RUN, commit ${SHA:0:7}_"
echo ""

render_section() { # <severity> <heading>
  local sev="$1" head="$2" rows
  rows="$(grep "\"severity\":\"$sev\"" "$FILE" 2>/dev/null || true)"
  [ -z "$rows" ] && return
  echo "### $head"
  printf '%s\n' "$rows" | jq -r '"- **\(.check)** — \(.file):\(.line) — \(.message)\n  - Fix: \(.fix)"'
  echo ""
}

render_section hard "🛑 Blocking (must fix to merge)"
render_section soft "💡 Suggestions (advisory)"
echo "<sub>Auto-generated by skill-policy.yml; updated each push. See .github/skill-policy.md</sub>"
